### ISSUE TITLE
Myanmar flag is wrong.

### ISSUE THREAD

**Issue by dagger11** [togisoft/jetpack_compose_country_code_picker#16]

**Comment by dagger11** [comment]
Flag for Myanmar country is wrong.

**Comment by dagger11** [comment]
example phone number should also be in 10 digits. Example-  9 712 345 678

**Comment by togisoft** [comment]
Okey thank you I will fix it

16 Kas 2022 Çar 08:17 tarihinde Pyae Phyo Kyaw ***@***.***>
şunu yazdı:

**Comment by togisoft** [comment]
Bug Fixed, you can check
