### ISSUE TITLE
Why the hell you changed so much API from 1.3 to 1.4?

### ISSUE THREAD

**Issue by st4ycool** [togisoft/jetpack_compose_country_code_picker#17]
Have you ever heard of SOLID? This library is a joke

**Comment by adukugideon** [comment]
You can make your point without insults or you can just go ahead and create your own library

**Comment by st4ycool** [comment]
I am very sorry for insults. It's just frustrating that or I am having compose crash on 1.3, or I have to spend time to migrate to your new api...

**Comment by togisoft** [comment]
> I am very sorry for insults. It's just frustrating that or I am having compose crash on 1.3, or I have to spend time to migrate to your new api...

The old API codes were not clean. Because I wrote it when I was just starting Jetpack Compose. I cleared the unnecessary codes now. The old version was causing problems with new Android updates. So I made changes.
