### ISSUE TITLE
Required an parameter to handle trailing icon visibility

### ISSUE THREAD

**Issue by SanushRadalage** [togisoft/jetpack_compose_country_code_picker#34]
![Screenshot 2023-06-27 at 06 16 27](https://github.com/togisoft/jetpack_compose_country_code_picker/assets/44916860/ba584043-05e5-451b-8c80-cdac6d3b989d)

**Comment by togisoft** [comment]
I am no longer developing. You can find the new version here.
https://github.com/jump-sdk/jetpack_compose_country_code_picker_emoji
