### ISSUE TITLE
South Korea Hint Error

### ISSUE THREAD

**Issue by JiSeokYeom** [togisoft/jetpack_compose_country_code_picker#35]
I'm currently living in South Korea, and the texthint should come out as 010-0000-0000, but there seems to be an issue that comes out as -2000-0000.

Library version 1.1.4
 
Device Samsung s8+
Android version 9
<img src="https://github.com/togisoft/jetpack_compose_country_code_picker/assets/38849158/09224bb9-6f47-4011-b7ee-d00618c0fed5" width="50%" height="50%"/>

**Comment by togisoft** [comment]
I am no longer developing. You can find the new version here.
https://github.com/jump-sdk/jetpack_compose_country_code_picker_emoji
