### ISSUE TITLE
I cannot set TextField to according to my design.

### ISSUE THREAD

**Issue by deepbmv** [togisoft/jetpack_compose_country_code_picker#5]
I really liked this library but in my latest project I need to use it as text field that have single line not rounded border. I am unable to add Single line like

 `

 TextField(
                value = password.value,
                colors = TextFieldDefaults.textFieldColors(
                    backgroundColor = Color.White,
                    focusedIndicatorColor = brc_green_color,
                    cursorColor = brc_green_color,
                    disabledPlaceholderColor = brc_green_color,
                    unfocusedIndicatorColor = brc_green_color
                ),
                onValueChange = {
                    if (passwordErrorState.value) {
                        passwordErrorState.value = false
                    }
                    password.value = it
                },
                isError = passwordErrorState.value,
                modifier = Modifier.fillMaxWidth(),
                label = {
                    Text(text = "Enter Password*")
                },
                trailingIcon = {
                    IconButton(onClick = {
                        passwordVisibility.value = !passwordVisibility.value
                    }) {

                    }
                },
                visualTransformation = if (passwordVisibility.value) PasswordVisualTransformation() else VisualTransformation.None
            )

`

I want to use exactly like above text-field. can anyone help?

**Comment by togisoft** [comment]
Sorry for the late reply. Can you show me an example visually?
