### ISSUE TITLE
error

### ISSUE THREAD

**Issue by aboudmahmoud** [togisoft/jetpack_compose_country_code_picker#8]
java.lang.NoSuchMethodError: No direct method <init>(ZZLandroidx/compose/ui/window/SecureFlagPolicy;ZILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Landroidx/compose/ui/window/DialogProperties; or its super classes (declaration of 'androidx.compose.ui.window.DialogProperties' appears in /data/app/com.example.bikiya-9aKEJDChoFqll2l-k0MTTg==/base.apk)
 at com.togitech.ccp.component.TogiCodePicker.TogiCodeDialog-9JTe1hw(TogiCodePicker.kt:98)

there is a problem with the dialog I think

**Comment by togisoft** [comment]
Can you share the kotlin gradle and other plugin versions you use?

**Comment by aboudmahmoud** [comment]
https://codeshare.io/0gzyPN 

https://codeshare.io/Adr9nl

**Comment by togisoft** [comment]
You can review the gradle files I have attached below. It works flawlessly.

https://codeshare.io/BAye4n
https://codeshare.io/JbDkBK

![country_code](https://user-images.githubusercontent.com/60444557/194749939-8f692005-3505-416a-a80d-50e9a63b1c3f.PNG)

**Comment by Android1500** [comment]
I also face same issue when use kotlinCompilerExtensionVersion 1.3.2 any fix for this?

**Comment by togisoft** [comment]
Change kotlinCompilerExtensionVersion 1.1.1 
I will update about it in the future

**Comment by Android1500** [comment]
> Change kotlinCompilerExtensionVersion 1.1.1 
> 
> I will update about it in the future
> 
> 

In my case it will impact other plugin so move to 1.1.1 in not right option

**Comment by aboudmahmoud** [comment]
> 

I did same as u say but it didnt work

**Comment by togisoft** [comment]
All problems have been fixed with the new update. You can check

**Comment by Android1500** [comment]
> All problems have been fixed with the new update. You can check
> 
> 

Thanks for update I just implemented it my new app.

**Comment by aboudmahmoud** [comment]
Thank you , It works
