### ISSUE TITLE
APP crashed when i click on flag

### ISSUE THREAD

**Issue by TuleSimon** [togisoft/jetpack_compose_country_code_picker#9]
when i click on the flag icon in the textfield my application crashes showing the error below:

 java.lang.NoSuchMethodError: No direct method <init>(ZZLandroidx/compose/ui/window/SecureFlagPolicy;ZILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Landroidx/compose/ui/window/DialogProperties; or its super classes (declaration of 'androidx.compose.ui.window.DialogProperties' appears in /data/data/com.scud.scuddriver/code_cache/.overlay/base.apk/classes15.dex)

**Comment by togisoft** [comment]
All problems have been fixed with the new update. You can check
